package energy.simulation;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableDigraph;

public class ExperimentalFrame extends ViewableDigraph {
	private final double OBSERVATION_TIME = 1;

	public ExperimentalFrame(String name) {
		super(name);
		experimentalFrameConstruct();
	}

	public ExperimentalFrame() {
		super("ExperimentalFrame");
		experimentalFrameConstruct();
	}

	private void experimentalFrameConstruct() {
		addInport("start");
		addInport("inFromHouse");
		addInport("inFromGrid");
		addOutport("outFromGenerator");
		addOutport("outFromTrancducer");

		ViewableAtomic generator = new Generator();
		ViewableAtomic trancducer = new Trancducer("Trancducer", OBSERVATION_TIME);

		add(generator);
		add(trancducer);

		initialize();

		addCoupling(this, "start", generator, "start");
		addCoupling(this, "inFromHouse", trancducer, "inFromHouse");
		addCoupling(this, "inFromGrid", trancducer, "inFromGrid");
		addCoupling(generator, "outFromEXPF", this, "outFromGenerator");
		addCoupling(trancducer, "out", this, "outFromTrancducer");
		addCoupling(trancducer, "out", generator, "stop");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 332);
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(-32, 119));
        ((ViewableComponent)withName("Trancducer")).setPreferredLocation(new Point(-76, 43));
    }
}
