package energy.simulation;

import java.awt.*;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class HomeAutomationSystem extends ViewableDigraph {

	public HomeAutomationSystem(String name) {
		super(name);
		homeAutomationConstruct();
	}

	public HomeAutomationSystem() {
		super("HomeAutomationSystem");
		homeAutomationConstruct();
	}

	private void homeAutomationConstruct() {

		addInport("in");
		addOutport("outOfSimulation");

		ViewableAtomic generator = new Generator();
		ViewableAtomic trancuder = new Trancducer();
		ViewableAtomic pv = new PhotoVoltaicPanel("PV", 1);
		ViewableAtomic lu = new LogicUnit("LU");
		ViewableAtomic bat = new Battery("Battery", 3, 5000);
		ViewableAtomic car = new ElectricCar();
		ViewableAtomic grid = new ExternalPowerGrid();
		ViewableAtomic house = new House("House");

		add(generator);
		add(trancuder);
		add(pv);
		add(lu);
		add(bat);
		add(car);
		add(grid);
		add(house);

		initialize();

		addCoupling(this, "in", generator, "start");
		addCoupling(generator, "outFromEXPF", pv, "inFromEXPF");
		addCoupling(pv, "outToLU", lu, "inFromPVPanel");
		addCoupling(lu, "outToBattery", bat, "inFromLU");
		addCoupling(bat, "outExtraToLU", lu, "inExtraFromBattery");
		addCoupling(lu, "outToEV", car, "inFromLU1");
		addCoupling(car, "carOverflow", lu, "inExtraFromEV");
		addCoupling(lu, "outToEG", grid, "inFromLU");

		addCoupling(lu, "outRequestEnergy", bat, "inFromLURequest");
		addCoupling(bat, "outToLU", lu, "inFromBattery");
		addCoupling(lu, "outToHouse", house, "inFromLU");
		addCoupling(house, "outToEXPF", trancuder, "inFromHouse");
		addCoupling(grid, "outToTrancducer", trancuder, "inFromGrid");
		addCoupling(trancuder, "out", this, "outOfSimulation");

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1048, 332);
        ((ViewableComponent)withName("PV")).setPreferredLocation(new Point(124, 98));
        ((ViewableComponent)withName("Tesla Model s")).setPreferredLocation(new Point(655, 161));
        ((ViewableComponent)withName("Battery")).setPreferredLocation(new Point(428, 233));
        ((ViewableComponent)withName("LU")).setPreferredLocation(new Point(344, 81));
        ((ViewableComponent)withName("House")).setPreferredLocation(new Point(663, 44));
        ((ViewableComponent)withName("Trancducer")).setPreferredLocation(new Point(-56, 33));
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(13, 162));
        ((ViewableComponent)withName("External Grid")).setPreferredLocation(new Point(204, 255));
    }
}
